apiVersion: v1
kind: Pod
metadata:
  name: fiap-db
  labels:
    app: fiap-db
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: tadriano
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: batatafrita
