apiVersion: v1
kind: Pod
metadata:
  name: fiap-pod
  labels:
        app: fiap-pod
spec:
  containers:
    - name: c-fiap-pod
      image: tadrianonet/angularenv
      ports:
        - containerPort: 80
      env:
        - name: URL_IMAGEM
          value: "https://br.web.img3.acsta.net/newsv7/20/02/03/22/01/2947023.jpg"
