apiVersion: v1
kind: Pod
metadata:
  name: fiap-pod2
  labels:
    app: fiap-pod2
spec:
  containers:
    - name: c-fiap-pod2
      image: tadrianonet/angularenv
      ports:
        - containerPort: 80
      env:
        - name: URL_IMAGEM
          valueFrom:
            secretKeyRef:
              name: opaque-secret-image
              key: URL_IMAGEM
