apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiap-pv-mongo
  labels:
    name: fiap-pv-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/thiagoadriano/Documents/curso_kubernetes/aula_6/exemplo_4/data