apiVersion: v1
kind: Pod
metadata:
  name: api2-pod
  labels:
        app: api2-pod
spec:
  containers:
  - name: api2-pod-config
    image: tadrianonet/apiexternal
    ports:
    - containerPort: 3000