kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch-pod
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31300  
      name: rest
    - port: 9300
      targetPort: 9300
      name: inter-node
