apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-pod
  labels:
    app: elasticsearch-pod
spec:
  containers:
    - name: elasticsearch-container
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
      env:
        - name: discovery.type
          value: single-node
      ports:
        - containerPort: 9200
          protocol: TCP
