version: '3'

services:
  app-node:
    container_name: node-fiap
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-fiap
    environment:
      - NODE_ENV=production
      - PROMETHEUS_ENDPOINT=http://prometheus:9090

  prometheus-fiap:
    container_name: prometheus-fiap
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-fiap:
    container_name: grafana-fiap
    image: grafana/grafana:8.1.5
    ports:
      - "3001:3000"          
    volumes:
      - ./grafana/data:/var/lib/grafana