apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-news
  labels:
    app: fiap-news
spec:
  template:
    metadata:
      name: fiap-news
      labels:
        app: fiap-news
    spec:
      containers:
        - name: fiap-news-container
          image: tadrianonet/pageexample
          ports:
            - containerPort: 80         
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
  replicas: 1
  selector:
    matchLabels:
      app: fiap-news
