apiVersion: v1
kind: Service
metadata:
  name: fiap-news-service
spec:
  type: NodePort
  selector:
    app: fiap-news
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31200