apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-nodeport-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32013
  selector:
    app: grafana
  type: NodePort