apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-http-liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-http-liveness
  template:
    metadata:
      labels:
        app: fiap-http-liveness
    spec:
      containers:
      - name: c-container
        image: tadrianonet/configmap:v10
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 30
