apiVersion: v1
kind: Pod
metadata:
  name: apipod
  labels:
        app: apipod
spec:
  containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]